CREATE TABLE classification_rules (
    id              BIGSERIAL PRIMARY KEY,
    code            VARCHAR(64)  NOT NULL UNIQUE,
    name            VARCHAR(255) NOT NULL,
    description     TEXT,
    decision        VARCHAR(64)  NOT NULL DEFAULT 'ACCUMULATE',
    priority        INTEGER      NOT NULL DEFAULT 50,
    enabled         BOOLEAN      NOT NULL DEFAULT true,
    condition_type  VARCHAR(64)  NOT NULL DEFAULT 'KEYWORD_AND_LENGTH',
    keywords_json   JSONB        DEFAULT '[]'::jsonb,
    regex_json      JSONB        DEFAULT '[]'::jsonb,
    min_text_length INTEGER,
    max_text_length INTEGER,
    requires_link   BOOLEAN      DEFAULT false,
    requires_code_block BOOLEAN  DEFAULT false,
    requires_error_pattern   BOOLEAN DEFAULT false,
    requires_price_pattern   BOOLEAN DEFAULT false,
    requires_question_pattern BOOLEAN DEFAULT false,
    requires_solution_pattern BOOLEAN DEFAULT false,
    examples_json   JSONB        DEFAULT '[]'::jsonb,
    scoring_weights_json JSONB  DEFAULT '{}'::jsonb,
    version         INTEGER      NOT NULL DEFAULT 1,
    is_active       BOOLEAN      NOT NULL DEFAULT true,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_by      VARCHAR(128)
);

CREATE TABLE classification_rule_versions (
    id              BIGSERIAL PRIMARY KEY,
    rule_id         BIGINT       NOT NULL REFERENCES classification_rules(id) ON DELETE CASCADE,
    version         INTEGER      NOT NULL,
    snapshot_json   JSONB        NOT NULL,
    change_reason   TEXT,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by      VARCHAR(128),
    UNIQUE (rule_id, version)
);

INSERT INTO classification_rules (code, name, description, decision, priority, enabled, condition_type,
    keywords_json, regex_json, min_text_length, max_text_length,
    requires_link, requires_code_block, requires_error_pattern, requires_price_pattern,
    requires_question_pattern, requires_solution_pattern, examples_json, scoring_weights_json)
VALUES
('noise_suppress', 'Noise suppress',
 'Короткий чат, флуд, нет полезного сигнала',
 'SUPPRESS', 10, true, 'KEYWORD_AND_LENGTH',
 '[]'::jsonb,
 '["^(ok|спасибо|thanks|\\+1|лол|ага|понял|поняла|ок|okay|yes|no|да|нет)[!.]*$"]'::jsonb,
 NULL, 18, false, false, false, false, false, false,
 '["сообщение длиной < 18 символов без hard сигналов"]'::jsonb,
 '{"textLengthWeight": 0.4, "noisePenalty": 0.3}'::jsonb),
('hard_signal', 'Hard signal',
 'Ошибка, цена, ограничение, сравнение, ссылка на ресурс',
 'CANDIDATE', 20, true, 'KEYWORD_AND_LENGTH',
 '[]'::jsonb,
 '[]'::jsonb,
 30, NULL, true, true, true, true, false, false,
 '["сообщение с ошибкой или ссылкой или кодом или ценой"]'::jsonb,
 '{"textLengthWeight": 0.2, "noisePenalty": 0.0}'::jsonb),
('accumulate', 'Accumulate',
 'Контекст полезен, но одного сообщения мало',
 'ACCUMULATE', 30, true, 'KEYWORD_AND_LENGTH',
 '[]'::jsonb,
 '[]'::jsonb,
 18, NULL, false, false, false, false, false, false,
 '["короткий полезный контекст, но без самостоятельной ценности"]'::jsonb,
 '{"textLengthWeight": 0.15, "noisePenalty": 0.1}'::jsonb);

INSERT INTO classification_rules (code, name, description, decision, priority, enabled, condition_type,
    keywords_json, regex_json, min_text_length, max_text_length,
    requires_link, requires_code_block, requires_error_pattern, requires_price_pattern,
    requires_question_pattern, requires_solution_pattern, examples_json, scoring_weights_json)
VALUES
('single_guide_ready', 'Single guide ready',
 'Одно сообщение содержит готовый гайд/фикс с пошаговым решением',
 'DIRECT_MATERIAL_READY', 40, true, 'KEYWORD_AND_LENGTH',
 '["шаг", "решение", "попробуй", "проверь", "убедись", "установи", "запусти", "открой", "создай", "настрой", "исправь"]'::jsonb,
 '["(?i)(проблема|причина|решение|ожидаемый результат|fix|solution|root cause|workaround)"]'::jsonb,
 200, NULL, true, true, true, false, false, true,
 '["сообщение с описанием проблемы, причины, решения и ожидаемого результата"]'::jsonb,
 '{"textLengthWeight": 0.15, "structureScore": 0.25, "guideHowToScore": 0.25, "troubleshootingScore": 0.25, "errorSignalScore": 0.15, "solutionSignalScore": 0.25, "codeOrCommandScore": 0.15, "linkScore": 0.10}'::jsonb),
('single_troubleshooting', 'Single troubleshooting',
 'Одно сообщение-фикс с error/log pattern',
 'SINGLE_MESSAGE_MATERIAL_CANDIDATE', 45, true, 'KEYWORD_AND_LENGTH',
 '["ошибка", "error", "exception", "failed", "timeout", "401", "403", "500", "not found", "invalid"]'::jsonb,
 '["(?i)(traceback|stack.?trace|exception|error|ошибк|исключ|не работает|cannot|fail|crash|bug)"]'::jsonb,
 100, NULL, false, true, true, false, false, false,
 '["сообщение с логом ошибки и описанием фикса"]'::jsonb,
 '{"textLengthWeight": 0.10, "errorSignalScore": 0.30, "troubleshootingScore": 0.30, "solutionSignalScore": 0.20, "codeOrCommandScore": 0.15}'::jsonb),
('single_resource', 'Single resource',
 'Одно сообщение-ссылка с описанием и ценой',
 'SINGLE_MESSAGE_MATERIAL_CANDIDATE', 50, true, 'KEYWORD_AND_LENGTH',
 '["цена", "price", "тариф", "стоимость", "доступ", "access", "купить", "подписка", "subscription"]'::jsonb,
 '["(?i)(\\$\\s?\\d+|\\d+\\s?(usd|eur|руб|₽)|pricing|платный|бесплатно|free|trial)"]'::jsonb,
 80, NULL, true, false, false, true, false, false,
 '["сообщение со ссылкой на сервис/инструмент и его ценой"]'::jsonb,
 '{"textLengthWeight": 0.10, "resourceSignalScore": 0.35, "priceAccessSignalScore": 0.35, "linkScore": 0.20}'::jsonb),
('single_qa', 'Single Q&A',
 'Одно сообщение с вопросом и ценным ответом',
 'SINGLE_MESSAGE_MATERIAL_CANDIDATE', 55, true, 'KEYWORD_AND_LENGTH',
 '["как", "how", "почему", "why", "что делать", "помогите", "help"]'::jsonb,
 '["(?i)(решение|answer|fix|попробуй|нужно|use|install|run|нашёл|нашел|решил|сделал)"]'::jsonb,
 100, NULL, false, false, false, false, true, true,
 '["вопрос с ответом/решением"]'::jsonb,
 '{"textLengthWeight": 0.10, "questionAnswerScore": 0.45, "solutionSignalScore": 0.25, "troubleshootingScore": 0.15}'::jsonb);
